# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Evelyn

on:
  push:
    branches: [ "main" ]

jobs:
  build-firefox:
    runs-on: ubuntu-latest
    env:
      BROWSER: firefox
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 8
      uses: actions/setup-node@v4
      with:
        node-version: 8
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: ./package.sh
  build-chrome:
    runs-on: ubuntu-latest
    env:
      BROWSER: chrome
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 8
      uses: actions/setup-node@v4
      with:
        node-version: 8
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: ./package.sh

